package com.javg.cryptocurrencies.utils

import com.javg.cryptocurrencies.R
import com.javg.cryptocurrencies.data.model.CRYDefaultBook

object CRYMockData {
    val bookDefaults = listOf(
        CRYDefaultBook("aave","Aave", R.drawable.ic_aave),
        CRYDefaultBook("ada","Cardano", R.drawable.ic_ada),
        CRYDefaultBook("algo","Algorand", R.drawable.ic_algo),
        CRYDefaultBook("ape","ApeCoin", R.drawable.ic_ape),
        CRYDefaultBook("arb","Arbitrum", R.drawable.ic_arb),
        CRYDefaultBook("atom","Cosmos", R.drawable.ic_atom),
        CRYDefaultBook("avax","Avalanche",R.drawable.ic_avax),
        CRYDefaultBook("axs","Axie Infinity",R.drawable.ic_axs),
        CRYDefaultBook("bal","Balancer",R.drawable.ic_bal),
        CRYDefaultBook("bar","BAR",R.drawable.ic_default_book),
        CRYDefaultBook("bat","Basic Attention Token",R.drawable.ic_bat),
        CRYDefaultBook("bch","Bitcoin cash",R.drawable.ic_bch),
        CRYDefaultBook("btc","Bitcoin",R.drawable.ic_btc),
        CRYDefaultBook("chz","Chiliz",R.drawable.ic_chz),
        CRYDefaultBook("comp","Compound",R.drawable.ic_comp),
        CRYDefaultBook("crv","Curve DAO",R.drawable.ic_crv),
        CRYDefaultBook("dai","DAI",R.drawable.ic_dai),
        CRYDefaultBook("doge","Dogecoin",R.drawable.ic_doge),
        CRYDefaultBook("dot","Polkadot",R.drawable.ic_dot),
        CRYDefaultBook("dydx","DYDX",R.drawable.ic_dydx),
        CRYDefaultBook("enj","Enjin Coin",R.drawable.ic_enj),
        CRYDefaultBook("eth","Ethereum",R.drawable.ic_eth),
        CRYDefaultBook("eur","EUR Crypto",R.drawable.ic_eur),
        CRYDefaultBook("ftm","Fantom",R.drawable.ic_ftm),
        CRYDefaultBook("gala","GALA",R.drawable.ic_gala),
        CRYDefaultBook("grt","The Graph",R.drawable.ic_grt),
        CRYDefaultBook("ldo","LIDO",R.drawable.ic_ldo),
        CRYDefaultBook("link","Chainlink",R.drawable.ic_link),
        CRYDefaultBook("lcr","Lucro",R.drawable.ic_lcr),
        CRYDefaultBook("ltc","Litecoin",R.drawable.ic_ltc),
        CRYDefaultBook("mana","MANA",R.drawable.ic_mana),
        CRYDefaultBook("matic","Matic",R.drawable.ic_polygon),
        CRYDefaultBook("mkr","Maker",R.drawable.ic_mkr),
        CRYDefaultBook("near","NEAR",R.drawable.ic_near),
        CRYDefaultBook("omg","OMG Network",R.drawable.ic_omg),
        CRYDefaultBook("paxg","Pax Gold",R.drawable.ic_paxg),
        CRYDefaultBook("pepe","Pepe",R.drawable.ic_pepe),
        CRYDefaultBook("pol","Polygon",R.drawable.ic_polygon),
        CRYDefaultBook("psg","PSG",R.drawable.ic_default_book),
        CRYDefaultBook("qnt","Quant",R.drawable.ic_qnt),
        CRYDefaultBook("sand","The Sandbo",R.drawable.ic_sand),
        CRYDefaultBook("shib","Shiba INU",R.drawable.ic_shiba),
        CRYDefaultBook("snx","Synthetix",R.drawable.ic_snx),
        CRYDefaultBook("sol","Solana",R.drawable.ic_sol),
        CRYDefaultBook("sushi","SushiSwap",R.drawable.ic_sushi),
        CRYDefaultBook("tigres","TIGRES",R.drawable.ic_default_book),
        CRYDefaultBook("trx","TRON",R.drawable.ic_tron),
        CRYDefaultBook("tusd","TrueUSD",R.drawable.ic_tusd),
        CRYDefaultBook("uni","Uniswap",R.drawable.ic_uni),
        CRYDefaultBook("usd","USD Coin",R.drawable.ic_usd),
        CRYDefaultBook("usdt","Tether",R.drawable.ic_usdt),
        CRYDefaultBook("xlm","Stellar",R.drawable.ic_xml),
        CRYDefaultBook("xrp","Ripple",R.drawable.ic_xrp),
        CRYDefaultBook("yfi","Yearn finance",R.drawable.ic_yfi))
}